# Generated by Django 4.0.3 on 2022-04-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0005_video_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='videooutput',
            name='detected_image',
            field=models.ImageField(default='', upload_to='upload_test_images/'),
        ),
    ]
