# Generated by Django 4.0.3 on 2022-04-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0006_videooutput_detected_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videooutput',
            name='detected_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='upload_test_images/'),
        ),
    ]
