# Generated by Django 4.0.3 on 2022-04-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0008_alter_video_videofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
